[tool.poetry]
name = "watermarkbot"
version = "1.5.3"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pyrogram = "^2.0.97"
hachoir = "^3.2.0"
aiofiles = "^22.1.0"
aiohttp = "^3.8.3"
dnspython = "^2.3.0"
humanfriendly = "^10.0"
psutil = "^5.9.4"
TgCrypto = "^1.2.5"
cachetools = "^5.3.0"
pymongo = "^4.3.3"
Pillow = "^9.4.0"
prettyconf = "^2.2.1"
pickledb-ujson = "^1.0.15"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
isort = "^5.12.0"
pre-commit = "^3.0.3"
pyclean = "^2.4.0"
pylint = "^2.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
