[tool.poetry]
name = "watermarkbot"
version = "1.5.3"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pyrogram = "^2.0.51"
hachoir = "^3.1.3"
aiofiles = "^22.1.0"
aiohttp = "^3.8.1"
dnspython = "^2.2.1"
humanfriendly = "^10.0"
psutil = "^5.9.2"
TgCrypto = "^1.2.3"
cachetools = "^5.2.0"
pymongo = "^4.2.0"
Pillow = "^9.2.0"
prettyconf = "^2.2.1"
pickledb-ujson = "^1.0.8"

[tool.poetry.dev-dependencies]
black = "^22.8.0"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pyclean = "^2.2.0"
pylint = "^2.15.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
